### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by WilliamEstrela** [songoda/EpicSpawners#1]
![image](https://cloud.githubusercontent.com/assets/5386302/24218426/1619ba4c-0f22-11e7-9ded-20db4d2ad7b5.png)

**Comment by songoda** [comment]
Please include this in your startup  "-XX:-OmitStackTraceInFastThrow" I can't read this otherwise.

**Comment by WilliamEstrela** [comment]
![image](https://cloud.githubusercontent.com/assets/5386302/24277905/12ef8d8a-101f-11e7-9390-9e78bcdc8740.png)
how?

**Comment by WilliamEstrela** [comment]
![image](https://cloud.githubusercontent.com/assets/5386302/24280741/c9ef12b4-1031-11e7-9262-4c58fea59810.png)

**Comment by songoda** [comment]
Resolved <3
