### ISSUE TITLE
Huge Dupe Glitch

### ISSUE THREAD

**Issue by IslandPvP** [songoda/EpicSpawners#4]
https://gyazo.com/18e9ecc7306a42227e2fe19312e33b77
It occours for Natural Mob spawners

**Comment by songoda** [comment]
I cant recreate that for it doesn't do that when I break a natural spawner.

IF you add me on skype @ Songoda I can streamline your support. At the moment it looks like it must be a confliction between EpicSpawners and another plugin that's handling spawners which we will need to troubleshoot and solve.
